theme = "after-dark"
baseURL = "http://antobiotics.github.io"
languageCode = "en-us"
title = "Les Antobitics, c'est pas automatique"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "About"
  weight = 3
  identifier = "aout"
  url = "/about/"
