theme = "after-dark"
baseURL = "http://antobiotics.github.io"
languageCode = "en-us"
title = "Les Antobiotics, c'est pas automatique"
enableEmoji = true


[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "About"
  url = "/about/"

[params]
  hide_author = true
  powered_by = false

[permalinks]
  post = "/:year/:month/:day/:title/"
